import TeslaImage from "../images/TeslaVideo.gif";

const projects = [
  {
    id: 1,
    title: "Tesla Clone",
    demo: "https://61c3985f4bd53f988b189ed1--boring-ritchie-aede20.netlify.app/",
    source: "https://github.com/Nlouis38/tesla-clone",
    img: TeslaImage,
    category: "Web Development",
  },
  {
    id: 2,
    title: "Blackjack",
    demo: "",
    source: "https://github.com/Nlouis38/BlackJack",
    img: "",
    category: "Games",
  },
  {
    id: 3,
    title: "Chrome Extension",
    demo: "",
    source: "https://github.com/Nlouis38/chrom-extension",
    img: "",
    category: "Web Development",
  },
  {
    id: 4,
    title: "Color Flipper",
    demo: "",
    source: "https://github.com/Nlouis38/color-flipper",
    img: "",
    category: "Web Development",
  },
  {
    id: 5,
    title: "Tour List",
    demo: "",
    source: "https://github.com/Nlouis38/01-birthday-reminder",
    img: "",
    category: "Web Development",
  },
  {
    id: 6,
    title: "Air Reel Cycle Testing",
    demo: "",
    source: "https://github.com/Nlouis38/01-birthday-reminder",
    img: "",
    category: "Arduino Automation",
  },
  {
    id: 7,
    title: "Smart Door Locks",
    demo: "",
    source: "https://github.com/Nlouis38/01-birthday-reminder",
    img: "",
    category: "Arduino Automation",
  },
  {
    id: 8,
    title: "Smart Faucets Cycle Testing",
    demo: "",
    source: "https://github.com/Nlouis38/01-birthday-reminder",
    img: "",
    category: "Arduino Automation",
  },
  {
    id: 9,
    title: "Flashlight Cycling",
    demo: "",
    source: "https://github.com/Nlouis38/01-birthday-reminder",
    img: "",
    category: "Arduino Automation",
  },
  {
    id: 10,
    title: "Staple Gun Cycling",
    demo: "",
    source: "https://github.com/Nlouis38/01-birthday-reminder",
    img: "",
    category: "High-Level Automation",
  },
  {
    id: 11,
    title: "Digital Waterfall",
    demo: "",
    source: "https://github.com/Nlouis38/01-birthday-reminder",
    img: "",
    category: "High-Level Automation",
  },
  {
    id: 12,
    title: "Object Detection and Measurement",
    demo: "",
    source: "https://github.com/Nlouis38/01-birthday-reminder",
    img: "",
    category: "Machine Learning/AI",
  },
];
export default projects;
